import * as fs from "fs";
import * as path from "path";

const MAX_PER_FILE_CHARS = 10 * 1024;  // 10KB per file
const MAX_TOTAL_CHARS = 50 * 1024;     // 50KB total

const BINARY_EXTENSIONS = /\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|pdf|zip|tar|gz|bmp|mp3|mp4|avi|mov|exe|dll|so|dylib|o|class|jar|war|node_modules)$/i;

export interface ProjectContext {
  description: string;
  techStack: string[];
  codebaseLayout: string;
  existingDocs: string[];
  keyFiles: Array<{ path: string; summary: string }>;
}

/**
 * Discover project context from an existing repo.
 * Reads key files to understand what the project is, what tech it uses,
 * and what documentation already exists.
 */
export function discoverProjectContext(
  projectPath: string,
  maxTotalChars: number = MAX_TOTAL_CHARS
): ProjectContext {
  let usedChars = 0;

  const context: ProjectContext = {
    description: "",
    techStack: [],
    codebaseLayout: "",
    existingDocs: [],
    keyFiles: [],
  };

  // 1. README.md
  const readmePath = path.join(projectPath, "README.md");
  if (fs.existsSync(readmePath)) {
    try {
      const content = readFileBounded(readmePath);
      context.description = extractDescription(content);
      usedChars += content.length;
    } catch { /* skip */ }
  }

  // 2. Tech stack from package manifests
  context.techStack = detectTechStack(projectPath);

  // 3. Directory tree (top 2 levels)
  context.codebaseLayout = buildDirectoryTree(projectPath, 2);
  usedChars += context.codebaseLayout.length;

  // 4. Existing docs
  const docsDir = path.join(projectPath, "docs");
  if (fs.existsSync(docsDir) && fs.statSync(docsDir).isDirectory()) {
    context.existingDocs = discoverDocs(docsDir, projectPath, maxTotalChars - usedChars);
    usedChars += context.existingDocs.reduce((sum, d) => sum + d.length, 0);
  }

  // 5. Key source files (entry points)
  if (usedChars < maxTotalChars) {
    context.keyFiles = discoverKeyFiles(projectPath, maxTotalChars - usedChars);
  }

  return context;
}

/**
 * Generate a project-context.md document from the discovered context.
 */
export function generateContextDocument(
  context: ProjectContext,
  projectName: string
): string {
  const sections: string[] = [];

  sections.push(`# Project Context — ${projectName}`);
  sections.push("");
  sections.push("*Generated by Raptor on project adoption. This provides context to sprint agents.*");
  sections.push("");

  sections.push("## Description");
  sections.push(context.description || "No description found.");
  sections.push("");

  sections.push("## Tech Stack");
  if (context.techStack.length > 0) {
    for (const tech of context.techStack) {
      sections.push(`- ${tech}`);
    }
  } else {
    sections.push("Not detected.");
  }
  sections.push("");

  sections.push("## Codebase Layout");
  sections.push("```");
  sections.push(context.codebaseLayout || "(empty)");
  sections.push("```");
  sections.push("");

  if (context.existingDocs.length > 0) {
    sections.push("## Existing Documentation");
    for (const doc of context.existingDocs) {
      sections.push(`- ${doc}`);
    }
    sections.push("");
  }

  if (context.keyFiles.length > 0) {
    sections.push("## Key Files");
    for (const file of context.keyFiles) {
      sections.push(`### ${file.path}`);
      sections.push(file.summary);
      sections.push("");
    }
  }

  return sections.join("\n");
}

// --- Internal helpers ---

function readFileBounded(filePath: string): string {
  const content = fs.readFileSync(filePath, "utf-8");
  return content.slice(0, MAX_PER_FILE_CHARS);
}

function extractDescription(readmeContent: string): string {
  // Take the first paragraph after the title
  const lines = readmeContent.split("\n");
  const descLines: string[] = [];
  let pastTitle = false;

  for (const line of lines) {
    if (line.startsWith("# ") && !pastTitle) {
      pastTitle = true;
      continue;
    }
    if (pastTitle) {
      if (line.trim() === "") {
        if (descLines.length > 0) break;
        continue;
      }
      descLines.push(line.trim());
    }
  }

  return descLines.join(" ") || readmeContent.slice(0, 200).trim();
}

function detectTechStack(projectPath: string): string[] {
  const stack: string[] = [];

  // package.json
  const pkgPath = path.join(projectPath, "package.json");
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      const allDeps = {
        ...pkg.dependencies,
        ...pkg.devDependencies,
      };
      const depNames = Object.keys(allDeps);
      stack.push(`Node.js (${depNames.length} dependencies)`);

      // Detect key frameworks
      if (allDeps.react) stack.push("React");
      if (allDeps.next) stack.push("Next.js");
      if (allDeps.express) stack.push("Express");
      if (allDeps.typescript || allDeps["ts-node"]) stack.push("TypeScript");
      if (allDeps.jest || allDeps.vitest) stack.push(allDeps.jest ? "Jest" : "Vitest");
    } catch { /* skip */ }
  }

  // pyproject.toml
  const pyprojectPath = path.join(projectPath, "pyproject.toml");
  if (fs.existsSync(pyprojectPath)) {
    try {
      const content = fs.readFileSync(pyprojectPath, "utf-8");
      stack.push("Python");
      if (content.includes("fastapi")) stack.push("FastAPI");
      if (content.includes("django")) stack.push("Django");
      if (content.includes("flask")) stack.push("Flask");
      if (content.includes("pytest")) stack.push("Pytest");
    } catch { /* skip */ }
  }

  // Cargo.toml
  const cargoPath = path.join(projectPath, "Cargo.toml");
  if (fs.existsSync(cargoPath)) {
    stack.push("Rust");
  }

  return stack;
}

function buildDirectoryTree(dirPath: string, maxDepth: number, currentDepth: number = 0, prefix: string = ""): string {
  if (currentDepth >= maxDepth) return "";

  const lines: string[] = [];
  try {
    const entries = fs.readdirSync(dirPath).filter((e) =>
      !e.startsWith(".") && e !== "node_modules" && e !== "__pycache__" && e !== "dist" && e !== "build" && e !== "target"
    ).sort();

    for (let i = 0; i < entries.length; i++) {
      const entry = entries[i];
      const fullPath = path.join(dirPath, entry);
      const isLast = i === entries.length - 1;
      const connector = isLast ? "└── " : "├── ";
      const childPrefix = isLast ? "    " : "│   ";

      try {
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
          lines.push(`${prefix}${connector}${entry}/`);
          const children = buildDirectoryTree(fullPath, maxDepth, currentDepth + 1, prefix + childPrefix);
          if (children) lines.push(children);
        } else {
          lines.push(`${prefix}${connector}${entry}`);
        }
      } catch {
        // Skip inaccessible entries
      }
    }
  } catch {
    // Skip unreadable directories
  }

  return lines.join("\n");
}

function discoverDocs(docsDir: string, projectPath: string, remainingChars: number): string[] {
  const docs: string[] = [];
  let used = 0;

  try {
    const files = fs.readdirSync(docsDir, { recursive: false }) as string[];
    for (const file of files) {
      if (used >= remainingChars) break;
      if (BINARY_EXTENSIONS.test(file)) continue;

      const fullPath = path.join(docsDir, file);
      try {
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
          docs.push(`${file}/ (directory)`);
        } else if (file.endsWith(".md")) {
          const content = readFileBounded(fullPath);
          const firstLine = content.split("\n").find((l) => l.startsWith("# "));
          const title = firstLine ? firstLine.replace(/^#+\s*/, "") : file;
          docs.push(`${file}: ${title}`);
          used += title.length;
        } else {
          docs.push(file);
        }
      } catch { /* skip */ }
    }
  } catch { /* skip */ }

  return docs;
}

function discoverKeyFiles(projectPath: string, remainingChars: number): Array<{ path: string; summary: string }> {
  const keyFiles: Array<{ path: string; summary: string }> = [];
  let used = 0;

  const entryPoints = [
    "src/index.ts", "src/index.js", "src/main.ts", "src/main.js",
    "src/app.ts", "src/app.js", "app.py", "main.py",
    "src/main.rs", "src/lib.rs",
  ];

  for (const ep of entryPoints) {
    if (used >= remainingChars) break;
    const fullPath = path.join(projectPath, ep);
    if (!fs.existsSync(fullPath)) continue;

    try {
      const content = fs.readFileSync(fullPath, "utf-8");
      const lines = content.split("\n").slice(0, 50);
      const summary = lines.join("\n");
      keyFiles.push({ path: ep, summary });
      used += summary.length;
    } catch { /* skip */ }
  }

  return keyFiles;
}
